services:
  shayfin:
    image: ghcr.io/tdeverx/shayfin:latest
    ports:
      - '${SHAYFIN_PORT:-3000}:3000'
    environment:
      ORIGIN: '${SHAYFIN_ORIGIN:-http://localhost:3000}'
    volumes:
      - shayfin-data:/data

volumes:
  shayfin-data:
